@startuml
interface IDatabaseContext {
    Collaborations : IMongoCollection<Event> <<get>>
    IsConnectionOpen() : bool
}
class DatabaseContext {
    - <<readonly>> _database : IMongoDatabase
    + DatabaseContext(settings:IDatabaseSettings)
    + Collaborations : IMongoCollection<Event> <<get>>
    + IsConnectionOpen() : bool
}
IDatabaseContext <|-- DatabaseContext
@enduml
