@startuml
class ProjectData {
    + Id : string <<get>> <<set>>
    + OwnerId : string <<get>> <<set>>
    + FreelancerId : string <<get>> <<set>>
    + ProjectContent : ProjectContentData <<get>> <<set>>
}
@enduml
