@startuml
class InvalidContact {
    + InvalidContact()
    + InvalidContact(message:string)
    + InvalidContact(message:string, inner:Exception)
    # InvalidContact(info:SerializationInfo, context:StreamingContext)
}
Exception <|-- InvalidContact
@enduml
