@startuml
interface IClient {
    HttpClientFactory : IHttpClientFactory <<get>>
}
class Client {
    + HttpClientFactory : IHttpClientFactory <<get>>
    + Client(httpClientFactory:IHttpClientFactory)
}
IClient <|-- Client
@enduml
