@startuml
class AuthRegisterData {
    + FirstName : string <<get>> <<set>>
    + LastName : string <<get>> <<set>>
    + Email : string <<get>> <<set>>
    + Password : string <<get>> <<set>>
}
class AuthRegisteredData {
    + Id : string <<get>> <<set>>
    + Email : string <<get>> <<set>>
    + FirstName : string <<get>> <<set>>
    + LastName : string <<get>> <<set>>
}
class AuthData {
    + Email : string <<get>> <<set>>
    + Password : string <<get>> <<set>>
}
class AuthenticatedData {
    + Id : string <<get>> <<set>>
    + Token : string <<get>> <<set>>
}
@enduml
