@startuml
class StartupDevelopment {
    + StartupDevelopment(configuration:IConfiguration)
    + Configuration : IConfiguration <<get>>
    + ConfigureServices(services:IServiceCollection) : void
    + Configure(app:IApplicationBuilder, env:IHostingEnvironment, loggerFactory:ILoggerFactory) : void
}
@enduml
