@startuml
class ProjectUpdateDto {
    + Id : string <<get>> <<set>>
    + OwnerId : string <<get>> <<set>>
    + FreelancerId : string <<get>> <<set>>
    + ProjectContent : ProjectContentDto <<get>> <<set>>
}
@enduml
