@startuml
interface IDatabaseContext {
    Chats : IMongoCollection<Message> <<get>>
    IsConnectionOpen() : bool
}
class DatabaseContext {
    - <<readonly>> _database : IMongoDatabase
    + DatabaseContext(settings:IDatabaseSettings)
    + Chats : IMongoCollection<Message> <<get>>
    + IsConnectionOpen() : bool
}
IDatabaseContext <|-- DatabaseContext
@enduml
