@startuml
class Project {
    + Id : string <<get>> <<set>>
    + OwnerId : string <<get>> <<set>>
    + FreelancerId : string <<get>> <<set>>
    + ProjectContent : ProjectContent <<get>> <<set>>
}
@enduml
