@startuml
class Cors <<static>> {
    + {static} AddMultipleDomainSupport(services:IServiceCollection) : IServiceCollection
    + {static} UseMultipleDomainSupport(app:IApplicationBuilder) : IApplicationBuilder
}
@enduml
