@startuml
interface IDatabaseContext {
    Audit : IMongoCollection<Audit> <<get>>
    IsConnectionOpen() : bool
}
class DatabaseContext {
    - <<readonly>> _database : IMongoDatabase
    + DatabaseContext(settings:IDatabaseSettings)
    + Audit : IMongoCollection<Audit> <<get>>
    + IsConnectionOpen() : bool
}
IDatabaseContext <|-- DatabaseContext
@enduml
