@startuml
class BidCreationDto {
    + ProjectId : string <<get>> <<set>>
    + FreelancerId : string <<get>> <<set>>
    + Message : string <<get>> <<set>>
    + Amount : decimal <<get>> <<set>>
}
@enduml
