@startuml
!include ./authentication-service/Application/Startup.puml
!include ./authentication-service/Application/StartupDevelopment.puml
!include ./authentication-service/Application/Program.puml
!include ./authentication-service/ApplicationUnitTests/UnitTest1.puml
!include ./collaboration-service/Application/Startup.puml
!include ./collaboration-service/Application/StartupDevelopment.puml
!include ./collaboration-service/Application/Program.puml
!include ./collaboration-service/ApplicationUnitTests/UnitTest1.puml
!include ./bidding-service/Application/Startup.puml
!include ./bidding-service/Application/StartupDevelopment.puml
!include ./bidding-service/Application/Program.puml
!include ./bidding-service/ApplicationUnitTests/UnitTest1.puml
!include ./files-service/Application/Startup.puml
!include ./files-service/Application/StartupDevelopment.puml
!include ./files-service/Application/Program.puml
!include ./files-service/ApplicationUnitTests/UnitTest1.puml
!include ./audit-service/Application/Startup.puml
!include ./audit-service/Application/StartupDevelopment.puml
!include ./audit-service/Application/Program.puml
!include ./audit-service/ApplicationUnitTests/UnitTest1.puml
!include ./payments-service/Application/Startup.puml
!include ./payments-service/Application/StartupDevelopment.puml
!include ./payments-service/Application/Program.puml
!include ./payments-service/ApplicationUnitTests/UnitTest1.puml
!include ./profile-service/Application/Startup.puml
!include ./profile-service/Application/StartupDevelopment.puml
!include ./profile-service/Application/Program.puml
!include ./profile-service/ApplicationUnitTests/DelegatingHandlerStub.puml
!include ./profile-service/ApplicationUnitTests/ProfileServiceTest.puml
!include ./chat-service/Application/Startup.puml
!include ./chat-service/Application/StartupDevelopment.puml
!include ./chat-service/Application/Program.puml
!include ./chat-service/ApplicationUnitTests/UnitTest1.puml
!include ./projects-service/Application/Startup.puml
!include ./projects-service/Application/StartupDevelopment.puml
!include ./projects-service/Application/Program.puml
!include ./projects-service/ApplicationUnitTests/UnitTest1.puml
!include ./users-service/Application/Startup.puml
!include ./users-service/Application/StartupDevelopment.puml
!include ./users-service/Application/Program.puml
!include ./users-service/ApplicationUnitTests/UnitTest1.puml
!include ./collaboration-broker-service/Application/Startup.puml
!include ./collaboration-broker-service/Application/StartupDevelopment.puml
!include ./collaboration-broker-service/Application/Program.puml
!include ./collaboration-broker-service/ApplicationUnitTests/UnitTest1.puml
!include ./authentication-service/Application/Helpers/AutoMapperProfile.puml
!include ./authentication-service/Application/Services/AuthenticationService.puml
!include ./authentication-service/Application/Database/DatabaseContext.puml
!include ./authentication-service/Application/Controllers/AuthenticationController.puml
!include ./authentication-service/Application/Controllers/HealthController.puml
!include ./authentication-service/Application/Repositories/AuthenticationRepository.puml
!include ./collaboration-service/Application/Exceptions/InvalidEvent.puml
!include ./collaboration-service/Application/Helpers/AutoMapperProfile.puml
!include ./collaboration-service/Application/Services/CollaborationService.puml
!include ./collaboration-service/Application/Database/DatabaseContext.puml
!include ./collaboration-service/Application/Controllers/CollaborationsController.puml
!include ./collaboration-service/Application/Controllers/HealthController.puml
!include ./collaboration-service/Application/Repositories/CollaborationRepository.puml
!include ./bidding-service/Application/Exceptions/InvalidBid.puml
!include ./bidding-service/Application/Helpers/AutoMapperProfile.puml
!include ./bidding-service/Application/Services/BidService.puml
!include ./bidding-service/Application/Database/DatabaseContext.puml
!include ./bidding-service/Application/Controllers/BiddingsController.puml
!include ./bidding-service/Application/Controllers/HealthController.puml
!include ./bidding-service/Application/Repositories/BidRepository.puml
!include ./files-service/Application/Exceptions/InvalidFile.puml
!include ./files-service/Application/Helpers/AutoMapperProfile.puml
!include ./files-service/Application/Services/FileService.puml
!include ./files-service/Application/Database/DatabaseContext.puml
!include ./files-service/Application/Controllers/FilesController.puml
!include ./files-service/Application/Controllers/HealthController.puml
!include ./files-service/Application/Repositories/FileRepository.puml
!include ./audit-service/Application/Exceptions/InvalidBid.puml
!include ./audit-service/Application/Helpers/AutoMapperProfile.puml
!include ./audit-service/Application/Database/DatabaseContext.puml
!include ./audit-service/Application/Controllers/AuditController.puml
!include ./audit-service/Application/Controllers/HealthController.puml
!include ./audit-service/Application/Repositories/AuditRepository.puml
!include ./payments-service/Application/Exceptions/InvalidPayment.puml
!include ./payments-service/Application/Exceptions/InvalidStripeUser.puml
!include ./payments-service/Application/Helpers/AutoMapperProfile.puml
!include ./payments-service/Application/Services/Paymentservice.puml
!include ./payments-service/Application/Database/DatabaseContext.puml
!include ./payments-service/Application/Controllers/PaymentsController.puml
!include ./payments-service/Application/Controllers/AccountsController.puml
!include ./payments-service/Application/Controllers/TransactionsController.puml
!include ./payments-service/Application/Controllers/WebhookController.puml
!include ./payments-service/Application/Controllers/HealthController.puml
!include ./payments-service/Application/Repositories/AccountsRepository.puml
!include ./payments-service/Application/Repositories/PaymentRepository.puml
!include ./profile-service/Application/Exceptions/InvalidProfile.puml
!include ./profile-service/Application/Helpers/AutoMapperProfile.puml
!include ./profile-service/Application/Services/ProfileService.puml
!include ./profile-service/Application/Database/DatabaseContext.puml
!include ./profile-service/Application/Controllers/ProfilesController.puml
!include ./profile-service/Application/Controllers/HealthController.puml
!include ./profile-service/Application/Repositories/ProfileRepository.puml
!include ./utility/Application.Utility/Models/Message.puml
!include ./utility/Application.Utility/Models/AppSettings.puml
!include ./utility/Application.Utility/Models/JaegerTracingOptions.puml
!include ./utility/Application.Utility/ClientLibrary/Client.puml
!include ./utility/Application.Utility/Startup/ApiDocumentation.puml
!include ./utility/Application.Utility/Startup/Settings.puml
!include ./utility/Application.Utility/Startup/Security.puml
!include ./utility/Application.Utility/Startup/Logging.puml
!include ./utility/Application.Utility/Startup/Cors.puml
!include ./utility/Application.Utility/Exception/ServiceDown.puml
!include ./utility/Application.Utility/Exception/UserNotFound.puml
!include ./utility/Application.Utility/Exception/EnvironmentNotSet.puml
!include ./utility/Application.Utility/Exception/ProjectNotFound.puml
!include ./utility/Application.Utility/Middleware/RequestMiddleWare.puml
!include ./utility/Application.Utility/Database/DatabaseSettings.puml
!include ./utility/Application.Utility/Database/MongoDbContext.puml
!include ./utility/Application.Utility/TestUtility/ProjectUtility.puml
!include ./utility/Application.Utility/TestUtility/AuthUtility.puml
!include ./chat-service/Application/Exceptions/InvalidEvent.puml
!include ./chat-service/Application/Exceptions/InvalidContact.puml
!include ./chat-service/Application/Helpers/AutoMapperProfile.puml
!include ./chat-service/Application/Services/Chatservice.puml
!include ./chat-service/Application/Database/DatabaseContext.puml
!include ./chat-service/Application/Controllers/ChatsController.puml
!include ./chat-service/Application/Controllers/HealthController.puml
!include ./chat-service/Application/Repositories/ChatRepository.puml
!include ./projects-service/Application/Exceptions/InvalidProject.puml
!include ./projects-service/Application/Helpers/AutoMapperProfile.puml
!include ./projects-service/Application/Services/ProjectService.puml
!include ./projects-service/Application/Database/DatabaseContext.puml
!include ./projects-service/Application/Controllers/ProjectsController.puml
!include ./projects-service/Application/Controllers/HealthController.puml
!include ./projects-service/Application/Repositories/ProjectRepository.puml
!include ./users-service/Application/Helpers/AutoMapperProfile.puml
!include ./users-service/Application/Services/UserService.puml
!include ./users-service/Application/Database/DatabaseContext.puml
!include ./users-service/Application/Controllers/UsersController.puml
!include ./users-service/Application/Controllers/HealthController.puml
!include ./users-service/Application/Repositories/UserRepository.puml
!include ./collaboration-broker-service/Application/Exceptions/InvalidBid.puml
!include ./collaboration-broker-service/Application/Helpers/AutoMapperProfile.puml
!include ./collaboration-broker-service/Application/Services/BrokerService.puml
!include ./collaboration-broker-service/Application/Database/DatabaseContext.puml
!include ./collaboration-broker-service/Application/Controllers/BrokerController.puml
!include ./collaboration-broker-service/Application/Controllers/HealthController.puml
!include ./collaboration-broker-service/Application/Repositories/BrokerRepository.puml
!include ./collaboration-broker-service/Application/States/ResultStates.puml
!include ./authentication-service/Application/Models/Entities/AuthUser.puml
!include ./authentication-service/Application/Models/DataTransferObjects/UserRegisteredDto.puml
!include ./authentication-service/Application/Models/DataTransferObjects/UserUpdateDto.puml
!include ./authentication-service/Application/Models/DataTransferObjects/UserDto.puml
!include ./authentication-service/Application/Models/DataTransferObjects/UserAuthenticatedDto.puml
!include ./authentication-service/Application/Models/DataTransferObjects/UserAuthenticationDto.puml
!include ./authentication-service/Application/Models/DataTransferObjects/UserRegistrationDto.puml
!include ./collaboration-service/Application/Models/Entities/Event.puml
!include ./collaboration-service/Application/Models/DataTransferObjects/EventDto.puml
!include ./collaboration-service/Application/Models/DataTransferObjects/EventCreationDto.puml
!include ./bidding-service/Application/Models/Entities/Bid.puml
!include ./bidding-service/Application/Models/DataTransferObjects/BidUpdateDto.puml
!include ./bidding-service/Application/Models/DataTransferObjects/BidCreationDto.puml
!include ./bidding-service/Application/Models/DataTransferObjects/BidDto.puml
!include ./files-service/Application/Models/Entities/File.puml
!include ./files-service/Application/Models/DataTransferObjects/FileDto.puml
!include ./audit-service/Application/Models/Entities/Audit.puml
!include ./audit-service/Application/Models/DataTransferObjects/AuditDto.puml
!include ./audit-service/Application/Models/DataTransferObjects/AuditCreationDto.puml
!include ./payments-service/Application/Models/Entities/Transaction.puml
!include ./payments-service/Application/Models/Entities/Account.puml
!include ./payments-service/Application/Models/DataTransferObjects/CreatedAccountDto.puml
!include ./payments-service/Application/Models/DataTransferObjects/AccountDto.puml
!include ./payments-service/Application/Models/DataTransferObjects/PaymentDto.puml
!include ./payments-service/Application/Models/DataTransferObjects/WithdrawCreationDto.puml
!include ./payments-service/Application/Models/DataTransferObjects/PayoutCreatedDto.puml
!include ./payments-service/Application/Models/DataTransferObjects/DepositCreationDto.puml
!include ./payments-service/Application/Models/DataTransferObjects/PaymentCreationDto.puml
!include ./payments-service/Application/Models/DataTransferObjects/TransferCreationDto.puml
!include ./payments-service/Application/Models/DataTransferObjects/PaymentIntentCreatedDto.puml
!include ./payments-service/Application/Models/DataTransferObjects/CreateAccountDto.puml
!include ./payments-service/Application/Models/DataTransferObjects/PaymentUpdateDto.puml
!include ./profile-service/Application/Models/Entities/Profile.puml
!include ./profile-service/Application/Models/DataTransferObjects/ProfileUpdateDto.puml
!include ./profile-service/Application/Models/DataTransferObjects/ProfileDto.puml
!include ./profile-service/Application/Models/DataTransferObjects/ProfileCreationDto.puml
!include ./utility/Application.Utility/ClientLibrary/Authentication/AuthClient.puml
!include ./utility/Application.Utility/ClientLibrary/Authentication/AuthData.puml
!include ./utility/Application.Utility/ClientLibrary/Payment/TransferData.puml
!include ./utility/Application.Utility/ClientLibrary/Payment/PaymentClient.puml
!include ./utility/Application.Utility/ClientLibrary/Project/ProjectClient.puml
!include ./utility/Application.Utility/ClientLibrary/Project/ProjectContentData.puml
!include ./utility/Application.Utility/ClientLibrary/Project/ProjectCreationData.puml
!include ./utility/Application.Utility/ClientLibrary/Project/ProjectData.puml
!include ./utility/Application.Utility/ClientLibrary/User/UserData.puml
!include ./utility/Application.Utility/ClientLibrary/User/UserClient.puml
!include ./utility/Application.Utility/ClientLibrary/Collaboration/CollaborationClient.puml
!include ./utility/Application.Utility/ClientLibrary/Collaboration/EventData.puml
!include ./utility/Application.Utility/ClientLibrary/Bid/BidClient.puml
!include ./utility/Application.Utility/ClientLibrary/Bid/BidData.puml
!include ./chat-service/Application/Models/Entities/Message.puml
!include ./chat-service/Application/Models/DataTransferObjects/AddContactDto.puml
!include ./chat-service/Application/Models/DataTransferObjects/MessageDto.puml
!include ./chat-service/Application/Models/DataTransferObjects/MessageCreationDto.puml
!include ./projects-service/Application/Models/Entities/ProjectContent.puml
!include ./projects-service/Application/Models/Entities/Project.puml
!include ./projects-service/Application/Models/DataTransferObjects/ProjectContentDto.puml
!include ./projects-service/Application/Models/DataTransferObjects/ProjectCreationDto.puml
!include ./projects-service/Application/Models/DataTransferObjects/ProjectUpdateDto.puml
!include ./projects-service/Application/Models/DataTransferObjects/ProjectDto.puml
!include ./users-service/Application/Models/Entities/User.puml
!include ./users-service/Application/Models/DataTransferObjects/UserUpdateDto.puml
!include ./users-service/Application/Models/DataTransferObjects/UserDto.puml
!include ./users-service/Application/Models/DataTransferObjects/UserCreationDto.puml
!include ./collaboration-broker-service/Application/Models/Entities/Result.puml
!include ./collaboration-broker-service/Application/Models/DataTransferObjects/BrokerUpdateDto.puml
!include ./collaboration-broker-service/Application/Models/DataTransferObjects/CompleteProjectDto.puml
!include ./collaboration-broker-service/Application/Models/DataTransferObjects/ResultCreationDto.puml
!include ./collaboration-broker-service/Application/Models/DataTransferObjects/BrokerDto.puml
!include ./collaboration-broker-service/Application/Models/DataTransferObjects/ProjectCompleteDto.puml
!include ./collaboration-broker-service/Application/Models/DataTransferObjects/PaidForResultDto.puml
!include ./collaboration-broker-service/Application/Models/DataTransferObjects/InitializedResultDto.puml
!include ./authentication-service/lib/utility/Application.Utility/Models/Message.puml
!include ./authentication-service/lib/utility/Application.Utility/Models/AppSettings.puml
!include ./authentication-service/lib/utility/Application.Utility/Models/JaegerTracingOptions.puml
!include ./authentication-service/lib/utility/Application.Utility/ClientLibrary/Client.puml
!include ./authentication-service/lib/utility/Application.Utility/Startup/ApiDocumentation.puml
!include ./authentication-service/lib/utility/Application.Utility/Startup/Settings.puml
!include ./authentication-service/lib/utility/Application.Utility/Startup/Security.puml
!include ./authentication-service/lib/utility/Application.Utility/Startup/Logging.puml
!include ./authentication-service/lib/utility/Application.Utility/Startup/Cors.puml
!include ./authentication-service/lib/utility/Application.Utility/Exception/ServiceDown.puml
!include ./authentication-service/lib/utility/Application.Utility/Exception/UserNotFound.puml
!include ./authentication-service/lib/utility/Application.Utility/Exception/EnvironmentNotSet.puml
!include ./authentication-service/lib/utility/Application.Utility/Middleware/RequestMiddleWare.puml
!include ./authentication-service/lib/utility/Application.Utility/Database/DatabaseSettings.puml
!include ./authentication-service/lib/utility/Application.Utility/Database/MongoDbContext.puml
!include ./collaboration-service/lib/utility/Application.Utility/Models/Message.puml
!include ./collaboration-service/lib/utility/Application.Utility/Models/AppSettings.puml
!include ./collaboration-service/lib/utility/Application.Utility/Models/JaegerTracingOptions.puml
!include ./collaboration-service/lib/utility/Application.Utility/ClientLibrary/Client.puml
!include ./collaboration-service/lib/utility/Application.Utility/Startup/ApiDocumentation.puml
!include ./collaboration-service/lib/utility/Application.Utility/Startup/Settings.puml
!include ./collaboration-service/lib/utility/Application.Utility/Startup/Security.puml
!include ./collaboration-service/lib/utility/Application.Utility/Startup/Logging.puml
!include ./collaboration-service/lib/utility/Application.Utility/Startup/Cors.puml
!include ./collaboration-service/lib/utility/Application.Utility/Exception/ServiceDown.puml
!include ./collaboration-service/lib/utility/Application.Utility/Exception/UserNotFound.puml
!include ./collaboration-service/lib/utility/Application.Utility/Exception/EnvironmentNotSet.puml
!include ./collaboration-service/lib/utility/Application.Utility/Exception/ProjectNotFound.puml
!include ./collaboration-service/lib/utility/Application.Utility/Middleware/RequestMiddleWare.puml
!include ./collaboration-service/lib/utility/Application.Utility/Database/DatabaseSettings.puml
!include ./collaboration-service/lib/utility/Application.Utility/Database/MongoDbContext.puml
!include ./bidding-service/lib/utility/Application.Utility/Models/Message.puml
!include ./bidding-service/lib/utility/Application.Utility/Models/AppSettings.puml
!include ./bidding-service/lib/utility/Application.Utility/Models/JaegerTracingOptions.puml
!include ./bidding-service/lib/utility/Application.Utility/ClientLibrary/Client.puml
!include ./bidding-service/lib/utility/Application.Utility/Startup/ApiDocumentation.puml
!include ./bidding-service/lib/utility/Application.Utility/Startup/Settings.puml
!include ./bidding-service/lib/utility/Application.Utility/Startup/Security.puml
!include ./bidding-service/lib/utility/Application.Utility/Startup/Logging.puml
!include ./bidding-service/lib/utility/Application.Utility/Startup/Cors.puml
!include ./bidding-service/lib/utility/Application.Utility/Exception/ServiceDown.puml
!include ./bidding-service/lib/utility/Application.Utility/Exception/UserNotFound.puml
!include ./bidding-service/lib/utility/Application.Utility/Exception/EnvironmentNotSet.puml
!include ./bidding-service/lib/utility/Application.Utility/Exception/ProjectNotFound.puml
!include ./bidding-service/lib/utility/Application.Utility/Middleware/RequestMiddleWare.puml
!include ./bidding-service/lib/utility/Application.Utility/Database/DatabaseSettings.puml
!include ./bidding-service/lib/utility/Application.Utility/Database/MongoDbContext.puml
!include ./files-service/lib/utility/Application.Utility/Models/Message.puml
!include ./files-service/lib/utility/Application.Utility/Models/AppSettings.puml
!include ./files-service/lib/utility/Application.Utility/Models/JaegerTracingOptions.puml
!include ./files-service/lib/utility/Application.Utility/ClientLibrary/Client.puml
!include ./files-service/lib/utility/Application.Utility/Startup/ApiDocumentation.puml
!include ./files-service/lib/utility/Application.Utility/Startup/Settings.puml
!include ./files-service/lib/utility/Application.Utility/Startup/Security.puml
!include ./files-service/lib/utility/Application.Utility/Startup/Logging.puml
!include ./files-service/lib/utility/Application.Utility/Startup/Cors.puml
!include ./files-service/lib/utility/Application.Utility/Exception/ServiceDown.puml
!include ./files-service/lib/utility/Application.Utility/Exception/UserNotFound.puml
!include ./files-service/lib/utility/Application.Utility/Exception/EnvironmentNotSet.puml
!include ./files-service/lib/utility/Application.Utility/Exception/ProjectNotFound.puml
!include ./files-service/lib/utility/Application.Utility/Middleware/RequestMiddleWare.puml
!include ./files-service/lib/utility/Application.Utility/Database/DatabaseSettings.puml
!include ./files-service/lib/utility/Application.Utility/Database/MongoDbContext.puml
!include ./audit-service/lib/utility/Application.Utility/Models/Message.puml
!include ./audit-service/lib/utility/Application.Utility/Models/AppSettings.puml
!include ./audit-service/lib/utility/Application.Utility/Models/JaegerTracingOptions.puml
!include ./audit-service/lib/utility/Application.Utility/ClientLibrary/Client.puml
!include ./audit-service/lib/utility/Application.Utility/Startup/ApiDocumentation.puml
!include ./audit-service/lib/utility/Application.Utility/Startup/Settings.puml
!include ./audit-service/lib/utility/Application.Utility/Startup/Security.puml
!include ./audit-service/lib/utility/Application.Utility/Startup/Logging.puml
!include ./audit-service/lib/utility/Application.Utility/Startup/Cors.puml
!include ./audit-service/lib/utility/Application.Utility/Exception/ServiceDown.puml
!include ./audit-service/lib/utility/Application.Utility/Exception/UserNotFound.puml
!include ./audit-service/lib/utility/Application.Utility/Exception/EnvironmentNotSet.puml
!include ./audit-service/lib/utility/Application.Utility/Exception/ProjectNotFound.puml
!include ./audit-service/lib/utility/Application.Utility/Middleware/RequestMiddleWare.puml
!include ./audit-service/lib/utility/Application.Utility/Database/DatabaseSettings.puml
!include ./audit-service/lib/utility/Application.Utility/Database/MongoDbContext.puml
!include ./payments-service/lib/utility/Application.Utility/Models/Message.puml
!include ./payments-service/lib/utility/Application.Utility/Models/AppSettings.puml
!include ./payments-service/lib/utility/Application.Utility/Models/JaegerTracingOptions.puml
!include ./payments-service/lib/utility/Application.Utility/ClientLibrary/Client.puml
!include ./payments-service/lib/utility/Application.Utility/Startup/ApiDocumentation.puml
!include ./payments-service/lib/utility/Application.Utility/Startup/Settings.puml
!include ./payments-service/lib/utility/Application.Utility/Startup/Security.puml
!include ./payments-service/lib/utility/Application.Utility/Startup/Logging.puml
!include ./payments-service/lib/utility/Application.Utility/Startup/Cors.puml
!include ./payments-service/lib/utility/Application.Utility/Exception/ServiceDown.puml
!include ./payments-service/lib/utility/Application.Utility/Exception/UserNotFound.puml
!include ./payments-service/lib/utility/Application.Utility/Exception/EnvironmentNotSet.puml
!include ./payments-service/lib/utility/Application.Utility/Exception/ProjectNotFound.puml
!include ./payments-service/lib/utility/Application.Utility/Middleware/RequestMiddleWare.puml
!include ./payments-service/lib/utility/Application.Utility/Database/DatabaseSettings.puml
!include ./payments-service/lib/utility/Application.Utility/Database/MongoDbContext.puml
!include ./profile-service/lib/utility/Application.Utility/Models/Message.puml
!include ./profile-service/lib/utility/Application.Utility/Models/AppSettings.puml
!include ./profile-service/lib/utility/Application.Utility/Models/JaegerTracingOptions.puml
!include ./profile-service/lib/utility/Application.Utility/ClientLibrary/Client.puml
!include ./profile-service/lib/utility/Application.Utility/Startup/ApiDocumentation.puml
!include ./profile-service/lib/utility/Application.Utility/Startup/Settings.puml
!include ./profile-service/lib/utility/Application.Utility/Startup/Security.puml
!include ./profile-service/lib/utility/Application.Utility/Startup/Logging.puml
!include ./profile-service/lib/utility/Application.Utility/Startup/Cors.puml
!include ./profile-service/lib/utility/Application.Utility/Exception/ServiceDown.puml
!include ./profile-service/lib/utility/Application.Utility/Exception/UserNotFound.puml
!include ./profile-service/lib/utility/Application.Utility/Exception/EnvironmentNotSet.puml
!include ./profile-service/lib/utility/Application.Utility/Exception/ProjectNotFound.puml
!include ./profile-service/lib/utility/Application.Utility/Middleware/RequestMiddleWare.puml
!include ./profile-service/lib/utility/Application.Utility/Database/DatabaseSettings.puml
!include ./profile-service/lib/utility/Application.Utility/Database/MongoDbContext.puml
!include ./chat-service/Application/obj/Debug/netcoreapp2.2/Application.AssemblyInfo.puml
!include ./chat-service/ApplicationUnitTests/obj/Debug/netcoreapp2.2/ApplicationUnitTests.AssemblyInfo.puml
!include ./chat-service/lib/utility/Application.Utility/Models/Message.puml
!include ./chat-service/lib/utility/Application.Utility/Models/AppSettings.puml
!include ./chat-service/lib/utility/Application.Utility/Models/JaegerTracingOptions.puml
!include ./chat-service/lib/utility/Application.Utility/ClientLibrary/Client.puml
!include ./chat-service/lib/utility/Application.Utility/Startup/ApiDocumentation.puml
!include ./chat-service/lib/utility/Application.Utility/Startup/Settings.puml
!include ./chat-service/lib/utility/Application.Utility/Startup/Security.puml
!include ./chat-service/lib/utility/Application.Utility/Startup/Logging.puml
!include ./chat-service/lib/utility/Application.Utility/Startup/Cors.puml
!include ./chat-service/lib/utility/Application.Utility/Exception/ServiceDown.puml
!include ./chat-service/lib/utility/Application.Utility/Exception/UserNotFound.puml
!include ./chat-service/lib/utility/Application.Utility/Exception/EnvironmentNotSet.puml
!include ./chat-service/lib/utility/Application.Utility/Exception/ProjectNotFound.puml
!include ./chat-service/lib/utility/Application.Utility/Middleware/RequestMiddleWare.puml
!include ./chat-service/lib/utility/Application.Utility/Database/DatabaseSettings.puml
!include ./chat-service/lib/utility/Application.Utility/Database/MongoDbContext.puml
!include ./projects-service/lib/utility/Application.Utility/Models/Message.puml
!include ./projects-service/lib/utility/Application.Utility/Models/AppSettings.puml
!include ./projects-service/lib/utility/Application.Utility/Models/JaegerTracingOptions.puml
!include ./projects-service/lib/utility/Application.Utility/ClientLibrary/Client.puml
!include ./projects-service/lib/utility/Application.Utility/Startup/ApiDocumentation.puml
!include ./projects-service/lib/utility/Application.Utility/Startup/Settings.puml
!include ./projects-service/lib/utility/Application.Utility/Startup/Security.puml
!include ./projects-service/lib/utility/Application.Utility/Startup/Logging.puml
!include ./projects-service/lib/utility/Application.Utility/Startup/Cors.puml
!include ./projects-service/lib/utility/Application.Utility/Exception/ServiceDown.puml
!include ./projects-service/lib/utility/Application.Utility/Exception/UserNotFound.puml
!include ./projects-service/lib/utility/Application.Utility/Exception/EnvironmentNotSet.puml
!include ./projects-service/lib/utility/Application.Utility/Exception/ProjectNotFound.puml
!include ./projects-service/lib/utility/Application.Utility/Middleware/RequestMiddleWare.puml
!include ./projects-service/lib/utility/Application.Utility/Database/DatabaseSettings.puml
!include ./projects-service/lib/utility/Application.Utility/Database/MongoDbContext.puml
!include ./projects-service/lib/utility/Application.Utility/TestUtility/ProjectUtility.puml
!include ./projects-service/lib/utility/Application.Utility/TestUtility/AuthUtility.puml
!include ./users-service/lib/utility/Application.Utility/Models/Message.puml
!include ./users-service/lib/utility/Application.Utility/Models/AppSettings.puml
!include ./users-service/lib/utility/Application.Utility/Models/JaegerTracingOptions.puml
!include ./users-service/lib/utility/Application.Utility/ClientLibrary/Client.puml
!include ./users-service/lib/utility/Application.Utility/Startup/ApiDocumentation.puml
!include ./users-service/lib/utility/Application.Utility/Startup/Settings.puml
!include ./users-service/lib/utility/Application.Utility/Startup/Security.puml
!include ./users-service/lib/utility/Application.Utility/Startup/Logging.puml
!include ./users-service/lib/utility/Application.Utility/Startup/Cors.puml
!include ./users-service/lib/utility/Application.Utility/Exception/ServiceDown.puml
!include ./users-service/lib/utility/Application.Utility/Exception/UserNotFound.puml
!include ./users-service/lib/utility/Application.Utility/Exception/EnvironmentNotSet.puml
!include ./users-service/lib/utility/Application.Utility/Middleware/RequestMiddleWare.puml
!include ./users-service/lib/utility/Application.Utility/Database/DatabaseSettings.puml
!include ./users-service/lib/utility/Application.Utility/Database/MongoDbContext.puml
!include ./collaboration-broker-service/lib/utility/Application.Utility/Models/Message.puml
!include ./collaboration-broker-service/lib/utility/Application.Utility/Models/AppSettings.puml
!include ./collaboration-broker-service/lib/utility/Application.Utility/Models/JaegerTracingOptions.puml
!include ./collaboration-broker-service/lib/utility/Application.Utility/ClientLibrary/Client.puml
!include ./collaboration-broker-service/lib/utility/Application.Utility/Startup/ApiDocumentation.puml
!include ./collaboration-broker-service/lib/utility/Application.Utility/Startup/Settings.puml
!include ./collaboration-broker-service/lib/utility/Application.Utility/Startup/Security.puml
!include ./collaboration-broker-service/lib/utility/Application.Utility/Startup/Logging.puml
!include ./collaboration-broker-service/lib/utility/Application.Utility/Startup/Cors.puml
!include ./collaboration-broker-service/lib/utility/Application.Utility/Exception/ServiceDown.puml
!include ./collaboration-broker-service/lib/utility/Application.Utility/Exception/UserNotFound.puml
!include ./collaboration-broker-service/lib/utility/Application.Utility/Exception/EnvironmentNotSet.puml
!include ./collaboration-broker-service/lib/utility/Application.Utility/Exception/ProjectNotFound.puml
!include ./collaboration-broker-service/lib/utility/Application.Utility/Middleware/RequestMiddleWare.puml
!include ./collaboration-broker-service/lib/utility/Application.Utility/Database/DatabaseSettings.puml
!include ./collaboration-broker-service/lib/utility/Application.Utility/Database/MongoDbContext.puml
!include ./authentication-service/lib/utility/Application.Utility/ClientLibrary/User/UserData.puml
!include ./authentication-service/lib/utility/Application.Utility/ClientLibrary/User/UserClient.puml
!include ./collaboration-service/lib/utility/Application.Utility/ClientLibrary/Project/ProjectClient.puml
!include ./collaboration-service/lib/utility/Application.Utility/ClientLibrary/Project/ProjectContentData.puml
!include ./collaboration-service/lib/utility/Application.Utility/ClientLibrary/Project/ProjectData.puml
!include ./collaboration-service/lib/utility/Application.Utility/ClientLibrary/User/UserData.puml
!include ./collaboration-service/lib/utility/Application.Utility/ClientLibrary/User/UserClient.puml
!include ./bidding-service/lib/utility/Application.Utility/ClientLibrary/Payment/TransferData.puml
!include ./bidding-service/lib/utility/Application.Utility/ClientLibrary/Payment/PaymentClient.puml
!include ./bidding-service/lib/utility/Application.Utility/ClientLibrary/Project/ProjectClient.puml
!include ./bidding-service/lib/utility/Application.Utility/ClientLibrary/Project/ProjectContentData.puml
!include ./bidding-service/lib/utility/Application.Utility/ClientLibrary/Project/ProjectData.puml
!include ./bidding-service/lib/utility/Application.Utility/ClientLibrary/User/UserData.puml
!include ./bidding-service/lib/utility/Application.Utility/ClientLibrary/User/UserClient.puml
!include ./bidding-service/lib/utility/Application.Utility/ClientLibrary/Collaboration/CollaborationClient.puml
!include ./bidding-service/lib/utility/Application.Utility/ClientLibrary/Collaboration/EventData.puml
!include ./bidding-service/lib/utility/Application.Utility/ClientLibrary/Bid/BidClient.puml
!include ./bidding-service/lib/utility/Application.Utility/ClientLibrary/Bid/BidData.puml
!include ./files-service/lib/utility/Application.Utility/ClientLibrary/Project/ProjectClient.puml
!include ./files-service/lib/utility/Application.Utility/ClientLibrary/Project/ProjectContentData.puml
!include ./files-service/lib/utility/Application.Utility/ClientLibrary/Project/ProjectData.puml
!include ./files-service/lib/utility/Application.Utility/ClientLibrary/User/UserData.puml
!include ./files-service/lib/utility/Application.Utility/ClientLibrary/User/UserClient.puml
!include ./audit-service/lib/utility/Application.Utility/ClientLibrary/Project/ProjectClient.puml
!include ./audit-service/lib/utility/Application.Utility/ClientLibrary/Project/ProjectContentData.puml
!include ./audit-service/lib/utility/Application.Utility/ClientLibrary/Project/ProjectData.puml
!include ./audit-service/lib/utility/Application.Utility/ClientLibrary/User/UserData.puml
!include ./audit-service/lib/utility/Application.Utility/ClientLibrary/User/UserClient.puml
!include ./payments-service/lib/utility/Application.Utility/ClientLibrary/Project/ProjectClient.puml
!include ./payments-service/lib/utility/Application.Utility/ClientLibrary/Project/ProjectContentData.puml
!include ./payments-service/lib/utility/Application.Utility/ClientLibrary/Project/ProjectData.puml
!include ./payments-service/lib/utility/Application.Utility/ClientLibrary/User/UserData.puml
!include ./payments-service/lib/utility/Application.Utility/ClientLibrary/User/UserClient.puml
!include ./profile-service/lib/utility/Application.Utility/ClientLibrary/Project/ProjectClient.puml
!include ./profile-service/lib/utility/Application.Utility/ClientLibrary/Project/ProjectContentData.puml
!include ./profile-service/lib/utility/Application.Utility/ClientLibrary/Project/ProjectData.puml
!include ./profile-service/lib/utility/Application.Utility/ClientLibrary/User/UserData.puml
!include ./profile-service/lib/utility/Application.Utility/ClientLibrary/User/UserClient.puml
!include ./chat-service/lib/utility/Application.Utility/ClientLibrary/Payment/TransferData.puml
!include ./chat-service/lib/utility/Application.Utility/ClientLibrary/Payment/PaymentClient.puml
!include ./chat-service/lib/utility/Application.Utility/ClientLibrary/Project/ProjectClient.puml
!include ./chat-service/lib/utility/Application.Utility/ClientLibrary/Project/ProjectContentData.puml
!include ./chat-service/lib/utility/Application.Utility/ClientLibrary/Project/ProjectData.puml
!include ./chat-service/lib/utility/Application.Utility/ClientLibrary/User/UserData.puml
!include ./chat-service/lib/utility/Application.Utility/ClientLibrary/User/UserClient.puml
!include ./chat-service/lib/utility/Application.Utility/ClientLibrary/Collaboration/CollaborationClient.puml
!include ./chat-service/lib/utility/Application.Utility/ClientLibrary/Collaboration/EventData.puml
!include ./chat-service/lib/utility/Application.Utility/ClientLibrary/Bid/BidClient.puml
!include ./chat-service/lib/utility/Application.Utility/ClientLibrary/Bid/BidData.puml
!include ./projects-service/lib/utility/Application.Utility/ClientLibrary/Authentication/AuthClient.puml
!include ./projects-service/lib/utility/Application.Utility/ClientLibrary/Authentication/AuthData.puml
!include ./projects-service/lib/utility/Application.Utility/ClientLibrary/Payment/TransferData.puml
!include ./projects-service/lib/utility/Application.Utility/ClientLibrary/Payment/PaymentClient.puml
!include ./projects-service/lib/utility/Application.Utility/ClientLibrary/Project/ProjectClient.puml
!include ./projects-service/lib/utility/Application.Utility/ClientLibrary/Project/ProjectContentData.puml
!include ./projects-service/lib/utility/Application.Utility/ClientLibrary/Project/ProjectCreationData.puml
!include ./projects-service/lib/utility/Application.Utility/ClientLibrary/Project/ProjectData.puml
!include ./projects-service/lib/utility/Application.Utility/ClientLibrary/User/UserData.puml
!include ./projects-service/lib/utility/Application.Utility/ClientLibrary/User/UserClient.puml
!include ./projects-service/lib/utility/Application.Utility/ClientLibrary/Collaboration/CollaborationClient.puml
!include ./projects-service/lib/utility/Application.Utility/ClientLibrary/Collaboration/EventData.puml
!include ./projects-service/lib/utility/Application.Utility/ClientLibrary/Bid/BidClient.puml
!include ./projects-service/lib/utility/Application.Utility/ClientLibrary/Bid/BidData.puml
!include ./users-service/lib/utility/Application.Utility/ClientLibrary/User/UserData.puml
!include ./users-service/lib/utility/Application.Utility/ClientLibrary/User/UserClient.puml
!include ./collaboration-broker-service/lib/utility/Application.Utility/ClientLibrary/Payment/TransferData.puml
!include ./collaboration-broker-service/lib/utility/Application.Utility/ClientLibrary/Payment/PaymentClient.puml
!include ./collaboration-broker-service/lib/utility/Application.Utility/ClientLibrary/Project/ProjectClient.puml
!include ./collaboration-broker-service/lib/utility/Application.Utility/ClientLibrary/Project/ProjectContentData.puml
!include ./collaboration-broker-service/lib/utility/Application.Utility/ClientLibrary/Project/ProjectData.puml
!include ./collaboration-broker-service/lib/utility/Application.Utility/ClientLibrary/User/UserData.puml
!include ./collaboration-broker-service/lib/utility/Application.Utility/ClientLibrary/User/UserClient.puml
!include ./collaboration-broker-service/lib/utility/Application.Utility/ClientLibrary/Collaboration/CollaborationClient.puml
!include ./collaboration-broker-service/lib/utility/Application.Utility/ClientLibrary/Collaboration/EventData.puml
!include ./collaboration-broker-service/lib/utility/Application.Utility/ClientLibrary/Bid/BidClient.puml
!include ./collaboration-broker-service/lib/utility/Application.Utility/ClientLibrary/Bid/BidData.puml
!include ./chat-service/lib/utility/Application.Utility/obj/Debug/netcoreapp2.2/Application.Utility.AssemblyInfo.puml
@enduml
